# Generated by Django 5.0.1 on 2024-01-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creer', models.DateTimeField(auto_now_add=True)),
                ('prenom', models.CharField(max_length=40)),
                ('nom', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=80)),
                ('num_tel', models.CharField(max_length=18)),
                ('adresse', models.CharField(max_length=40)),
                ('ville', models.CharField(max_length=40)),
                ('departement', models.CharField(max_length=40)),
                ('code_postal', models.CharField(max_length=10)),
            ],
        ),
    ]
